name: hack20_greatawait
description: Great Await (Flutter Hackathon 2020)
publish_to: 'none'
version: 1.0.0+1
authors:
  - Dhruvil Patel (Github= dhruvilp)
  - Paul John (Github= PJprogrammer)

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  groovin_material_icons: ^1.1.6
  humanitarian_icons: ^0.1.0
  flutter_launcher_icons: ^0.7.4
  font_awesome_flutter: ^8.5.0
  flare_flutter: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  pedantic: ^1.9.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - mock_data/

  fonts:
    - family: Quicksand 
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
